// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package record

var TableNames = struct {
	Bookmark            string
	BookmarkTagRelation string
	Entry               string
	Tag                 string
	User                string
}{
	Bookmark:            "bookmark",
	BookmarkTagRelation: "bookmark_tag_relation",
	Entry:               "entry",
	Tag:                 "tag",
	User:                "user",
}
