// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package record

var TableNames = struct {
	BookmarkTagRelations string
	Bookmarks            string
	Entries              string
	Tags                 string
	Users                string
}{
	BookmarkTagRelations: "bookmark_tag_relations",
	Bookmarks:            "bookmarks",
	Entries:              "entries",
	Tags:                 "tags",
	Users:                "users",
}
