// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package record

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testBookmarkTagRelations(t *testing.T) {
	t.Parallel()

	query := BookmarkTagRelations()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testBookmarkTagRelationsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BookmarkTagRelations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBookmarkTagRelationsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := BookmarkTagRelations().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BookmarkTagRelations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBookmarkTagRelationsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BookmarkTagRelationSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BookmarkTagRelations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBookmarkTagRelationsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := BookmarkTagRelationExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if BookmarkTagRelation exists: %s", err)
	}
	if !e {
		t.Errorf("Expected BookmarkTagRelationExists to return true, but got false.")
	}
}

func testBookmarkTagRelationsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	bookmarkTagRelationFound, err := FindBookmarkTagRelation(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if bookmarkTagRelationFound == nil {
		t.Error("want a record, got nil")
	}
}

func testBookmarkTagRelationsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = BookmarkTagRelations().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testBookmarkTagRelationsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := BookmarkTagRelations().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testBookmarkTagRelationsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	bookmarkTagRelationOne := &BookmarkTagRelation{}
	bookmarkTagRelationTwo := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, bookmarkTagRelationOne, bookmarkTagRelationDBTypes, false, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}
	if err = randomize.Struct(seed, bookmarkTagRelationTwo, bookmarkTagRelationDBTypes, false, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = bookmarkTagRelationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = bookmarkTagRelationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BookmarkTagRelations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testBookmarkTagRelationsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	bookmarkTagRelationOne := &BookmarkTagRelation{}
	bookmarkTagRelationTwo := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, bookmarkTagRelationOne, bookmarkTagRelationDBTypes, false, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}
	if err = randomize.Struct(seed, bookmarkTagRelationTwo, bookmarkTagRelationDBTypes, false, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = bookmarkTagRelationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = bookmarkTagRelationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BookmarkTagRelations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func bookmarkTagRelationBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *BookmarkTagRelation) error {
	*o = BookmarkTagRelation{}
	return nil
}

func bookmarkTagRelationAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *BookmarkTagRelation) error {
	*o = BookmarkTagRelation{}
	return nil
}

func bookmarkTagRelationAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *BookmarkTagRelation) error {
	*o = BookmarkTagRelation{}
	return nil
}

func bookmarkTagRelationBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *BookmarkTagRelation) error {
	*o = BookmarkTagRelation{}
	return nil
}

func bookmarkTagRelationAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *BookmarkTagRelation) error {
	*o = BookmarkTagRelation{}
	return nil
}

func bookmarkTagRelationBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *BookmarkTagRelation) error {
	*o = BookmarkTagRelation{}
	return nil
}

func bookmarkTagRelationAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *BookmarkTagRelation) error {
	*o = BookmarkTagRelation{}
	return nil
}

func bookmarkTagRelationBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *BookmarkTagRelation) error {
	*o = BookmarkTagRelation{}
	return nil
}

func bookmarkTagRelationAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *BookmarkTagRelation) error {
	*o = BookmarkTagRelation{}
	return nil
}

func testBookmarkTagRelationsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &BookmarkTagRelation{}
	o := &BookmarkTagRelation{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, false); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation object: %s", err)
	}

	AddBookmarkTagRelationHook(boil.BeforeInsertHook, bookmarkTagRelationBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	bookmarkTagRelationBeforeInsertHooks = []BookmarkTagRelationHook{}

	AddBookmarkTagRelationHook(boil.AfterInsertHook, bookmarkTagRelationAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	bookmarkTagRelationAfterInsertHooks = []BookmarkTagRelationHook{}

	AddBookmarkTagRelationHook(boil.AfterSelectHook, bookmarkTagRelationAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	bookmarkTagRelationAfterSelectHooks = []BookmarkTagRelationHook{}

	AddBookmarkTagRelationHook(boil.BeforeUpdateHook, bookmarkTagRelationBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	bookmarkTagRelationBeforeUpdateHooks = []BookmarkTagRelationHook{}

	AddBookmarkTagRelationHook(boil.AfterUpdateHook, bookmarkTagRelationAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	bookmarkTagRelationAfterUpdateHooks = []BookmarkTagRelationHook{}

	AddBookmarkTagRelationHook(boil.BeforeDeleteHook, bookmarkTagRelationBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	bookmarkTagRelationBeforeDeleteHooks = []BookmarkTagRelationHook{}

	AddBookmarkTagRelationHook(boil.AfterDeleteHook, bookmarkTagRelationAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	bookmarkTagRelationAfterDeleteHooks = []BookmarkTagRelationHook{}

	AddBookmarkTagRelationHook(boil.BeforeUpsertHook, bookmarkTagRelationBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	bookmarkTagRelationBeforeUpsertHooks = []BookmarkTagRelationHook{}

	AddBookmarkTagRelationHook(boil.AfterUpsertHook, bookmarkTagRelationAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	bookmarkTagRelationAfterUpsertHooks = []BookmarkTagRelationHook{}
}

func testBookmarkTagRelationsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BookmarkTagRelations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBookmarkTagRelationsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(bookmarkTagRelationColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := BookmarkTagRelations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBookmarkTagRelationToOneBookmarkUsingBookmark(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local BookmarkTagRelation
	var foreign Bookmark

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, bookmarkTagRelationDBTypes, false, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, bookmarkDBTypes, false, bookmarkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Bookmark struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.BookmarkID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Bookmark().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := BookmarkTagRelationSlice{&local}
	if err = local.L.LoadBookmark(ctx, tx, false, (*[]*BookmarkTagRelation)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Bookmark == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Bookmark = nil
	if err = local.L.LoadBookmark(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Bookmark == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testBookmarkTagRelationToOneTagUsingTag(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local BookmarkTagRelation
	var foreign Tag

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, bookmarkTagRelationDBTypes, false, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, tagDBTypes, false, tagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tag struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.TagID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Tag().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := BookmarkTagRelationSlice{&local}
	if err = local.L.LoadTag(ctx, tx, false, (*[]*BookmarkTagRelation)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Tag == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Tag = nil
	if err = local.L.LoadTag(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Tag == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testBookmarkTagRelationToOneSetOpBookmarkUsingBookmark(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a BookmarkTagRelation
	var b, c Bookmark

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bookmarkTagRelationDBTypes, false, strmangle.SetComplement(bookmarkTagRelationPrimaryKeyColumns, bookmarkTagRelationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, bookmarkDBTypes, false, strmangle.SetComplement(bookmarkPrimaryKeyColumns, bookmarkColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, bookmarkDBTypes, false, strmangle.SetComplement(bookmarkPrimaryKeyColumns, bookmarkColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Bookmark{&b, &c} {
		err = a.SetBookmark(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Bookmark != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.BookmarkTagRelations[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.BookmarkID != x.ID {
			t.Error("foreign key was wrong value", a.BookmarkID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.BookmarkID))
		reflect.Indirect(reflect.ValueOf(&a.BookmarkID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.BookmarkID != x.ID {
			t.Error("foreign key was wrong value", a.BookmarkID, x.ID)
		}
	}
}
func testBookmarkTagRelationToOneSetOpTagUsingTag(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a BookmarkTagRelation
	var b, c Tag

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bookmarkTagRelationDBTypes, false, strmangle.SetComplement(bookmarkTagRelationPrimaryKeyColumns, bookmarkTagRelationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, tagDBTypes, false, strmangle.SetComplement(tagPrimaryKeyColumns, tagColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, tagDBTypes, false, strmangle.SetComplement(tagPrimaryKeyColumns, tagColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Tag{&b, &c} {
		err = a.SetTag(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Tag != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.BookmarkTagRelations[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TagID != x.ID {
			t.Error("foreign key was wrong value", a.TagID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TagID))
		reflect.Indirect(reflect.ValueOf(&a.TagID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TagID != x.ID {
			t.Error("foreign key was wrong value", a.TagID, x.ID)
		}
	}
}

func testBookmarkTagRelationsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBookmarkTagRelationsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BookmarkTagRelationSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBookmarkTagRelationsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BookmarkTagRelations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	bookmarkTagRelationDBTypes = map[string]string{`ID`: `bigint`, `BookmarkID`: `bigint`, `TagID`: `bigint`}
	_                          = bytes.MinRead
)

func testBookmarkTagRelationsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(bookmarkTagRelationPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(bookmarkTagRelationAllColumns) == len(bookmarkTagRelationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BookmarkTagRelations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testBookmarkTagRelationsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(bookmarkTagRelationAllColumns) == len(bookmarkTagRelationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BookmarkTagRelation{}
	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BookmarkTagRelations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, bookmarkTagRelationDBTypes, true, bookmarkTagRelationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(bookmarkTagRelationAllColumns, bookmarkTagRelationPrimaryKeyColumns) {
		fields = bookmarkTagRelationAllColumns
	} else {
		fields = strmangle.SetComplement(
			bookmarkTagRelationAllColumns,
			bookmarkTagRelationPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := BookmarkTagRelationSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testBookmarkTagRelationsUpsert(t *testing.T) {
	t.Parallel()

	if len(bookmarkTagRelationAllColumns) == len(bookmarkTagRelationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLBookmarkTagRelationUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := BookmarkTagRelation{}
	if err = randomize.Struct(seed, &o, bookmarkTagRelationDBTypes, false); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BookmarkTagRelation: %s", err)
	}

	count, err := BookmarkTagRelations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, bookmarkTagRelationDBTypes, false, bookmarkTagRelationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BookmarkTagRelation struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BookmarkTagRelation: %s", err)
	}

	count, err = BookmarkTagRelations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
