// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package record

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testEntries(t *testing.T) {
	t.Parallel()

	query := Entries()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testEntriesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Entry{}
	if err = randomize.Struct(seed, o, entryDBTypes, true, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Entries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEntriesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Entry{}
	if err = randomize.Struct(seed, o, entryDBTypes, true, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Entries().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Entries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEntriesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Entry{}
	if err = randomize.Struct(seed, o, entryDBTypes, true, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EntrySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Entries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEntriesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Entry{}
	if err = randomize.Struct(seed, o, entryDBTypes, true, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := EntryExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Entry exists: %s", err)
	}
	if !e {
		t.Errorf("Expected EntryExists to return true, but got false.")
	}
}

func testEntriesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Entry{}
	if err = randomize.Struct(seed, o, entryDBTypes, true, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	entryFound, err := FindEntry(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if entryFound == nil {
		t.Error("want a record, got nil")
	}
}

func testEntriesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Entry{}
	if err = randomize.Struct(seed, o, entryDBTypes, true, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Entries().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testEntriesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Entry{}
	if err = randomize.Struct(seed, o, entryDBTypes, true, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Entries().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testEntriesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	entryOne := &Entry{}
	entryTwo := &Entry{}
	if err = randomize.Struct(seed, entryOne, entryDBTypes, false, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}
	if err = randomize.Struct(seed, entryTwo, entryDBTypes, false, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = entryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = entryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Entries().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testEntriesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	entryOne := &Entry{}
	entryTwo := &Entry{}
	if err = randomize.Struct(seed, entryOne, entryDBTypes, false, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}
	if err = randomize.Struct(seed, entryTwo, entryDBTypes, false, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = entryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = entryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Entries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func entryBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Entry) error {
	*o = Entry{}
	return nil
}

func entryAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Entry) error {
	*o = Entry{}
	return nil
}

func entryAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Entry) error {
	*o = Entry{}
	return nil
}

func entryBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Entry) error {
	*o = Entry{}
	return nil
}

func entryAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Entry) error {
	*o = Entry{}
	return nil
}

func entryBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Entry) error {
	*o = Entry{}
	return nil
}

func entryAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Entry) error {
	*o = Entry{}
	return nil
}

func entryBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Entry) error {
	*o = Entry{}
	return nil
}

func entryAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Entry) error {
	*o = Entry{}
	return nil
}

func testEntriesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Entry{}
	o := &Entry{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, entryDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Entry object: %s", err)
	}

	AddEntryHook(boil.BeforeInsertHook, entryBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	entryBeforeInsertHooks = []EntryHook{}

	AddEntryHook(boil.AfterInsertHook, entryAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	entryAfterInsertHooks = []EntryHook{}

	AddEntryHook(boil.AfterSelectHook, entryAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	entryAfterSelectHooks = []EntryHook{}

	AddEntryHook(boil.BeforeUpdateHook, entryBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	entryBeforeUpdateHooks = []EntryHook{}

	AddEntryHook(boil.AfterUpdateHook, entryAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	entryAfterUpdateHooks = []EntryHook{}

	AddEntryHook(boil.BeforeDeleteHook, entryBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	entryBeforeDeleteHooks = []EntryHook{}

	AddEntryHook(boil.AfterDeleteHook, entryAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	entryAfterDeleteHooks = []EntryHook{}

	AddEntryHook(boil.BeforeUpsertHook, entryBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	entryBeforeUpsertHooks = []EntryHook{}

	AddEntryHook(boil.AfterUpsertHook, entryAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	entryAfterUpsertHooks = []EntryHook{}
}

func testEntriesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Entry{}
	if err = randomize.Struct(seed, o, entryDBTypes, true, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Entries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEntriesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Entry{}
	if err = randomize.Struct(seed, o, entryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(entryColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Entries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEntryToManyBookmarks(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Entry
	var b, c Bookmark

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, entryDBTypes, true, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, bookmarkDBTypes, false, bookmarkColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, bookmarkDBTypes, false, bookmarkColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.EntryID = a.ID
	c.EntryID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Bookmarks().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.EntryID == b.EntryID {
			bFound = true
		}
		if v.EntryID == c.EntryID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := EntrySlice{&a}
	if err = a.L.LoadBookmarks(ctx, tx, false, (*[]*Entry)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Bookmarks); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Bookmarks = nil
	if err = a.L.LoadBookmarks(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Bookmarks); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testEntryToManyAddOpBookmarks(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Entry
	var b, c, d, e Bookmark

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, entryDBTypes, false, strmangle.SetComplement(entryPrimaryKeyColumns, entryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Bookmark{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, bookmarkDBTypes, false, strmangle.SetComplement(bookmarkPrimaryKeyColumns, bookmarkColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Bookmark{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddBookmarks(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.EntryID {
			t.Error("foreign key was wrong value", a.ID, first.EntryID)
		}
		if a.ID != second.EntryID {
			t.Error("foreign key was wrong value", a.ID, second.EntryID)
		}

		if first.R.Entry != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Entry != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Bookmarks[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Bookmarks[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Bookmarks().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testEntriesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Entry{}
	if err = randomize.Struct(seed, o, entryDBTypes, true, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testEntriesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Entry{}
	if err = randomize.Struct(seed, o, entryDBTypes, true, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EntrySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testEntriesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Entry{}
	if err = randomize.Struct(seed, o, entryDBTypes, true, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Entries().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	entryDBTypes = map[string]string{`ID`: `bigint`, `URL`: `varbinary`, `Titile`: `varchar`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`}
	_            = bytes.MinRead
)

func testEntriesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(entryPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(entryAllColumns) == len(entryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Entry{}
	if err = randomize.Struct(seed, o, entryDBTypes, true, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Entries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, entryDBTypes, true, entryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testEntriesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(entryAllColumns) == len(entryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Entry{}
	if err = randomize.Struct(seed, o, entryDBTypes, true, entryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Entries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, entryDBTypes, true, entryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(entryAllColumns, entryPrimaryKeyColumns) {
		fields = entryAllColumns
	} else {
		fields = strmangle.SetComplement(
			entryAllColumns,
			entryPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := EntrySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testEntriesUpsert(t *testing.T) {
	t.Parallel()

	if len(entryAllColumns) == len(entryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLEntryUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Entry{}
	if err = randomize.Struct(seed, &o, entryDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Entry: %s", err)
	}

	count, err := Entries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, entryDBTypes, false, entryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Entry struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Entry: %s", err)
	}

	count, err = Entries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
